import { Link } from 'react-router-dom'
import { ExternalLink } from 'lucide-react'
import ddiLogo from '../assets/icon.png'

export default function Footer() {
  const year = new Date().getFullYear()

  return (
    <footer className="footer" role="contentinfo">
      <div className="container">

        <div className="footer-grid">
          {/* Brand */}
          <div>
            <div className="footer-brand-name">
              <img src={ddiLogo} alt="" aria-hidden="true" style={{ width: 28, height: 28, objectFit: 'contain', flexShrink: 0 }} />
              DDIPredict Platform
            </div>
            <p className="footer-brand-desc">
              A machine learning–based clinical decision support system for drug-drug interaction
              severity prediction. Built on a Random Forest Classifier trained on 27,449 drug pairs
              from the DDInter database.
            </p>
            <span className="footer-version-badge">v1.0.0 — Research Release</span>
          </div>

          {/* Platform */}
          <div className="footer-col">
            <p className="footer-col-title">Platform</p>
            <Link to="/">Dashboard</Link>
            <Link to="/predict">Prediction Tool</Link>
            <Link to="/drugs">Drug Database</Link>
            <Link to="/analytics">Analytics</Link>
          </div>

          {/* Resources */}
          <div className="footer-col">
            <p className="footer-col-title">Resources</p>
            <Link to="/about">Documentation</Link>
            <Link to="/about">Methodology</Link>
            <a href="http://localhost:8000/docs" target="_blank" rel="noopener noreferrer">
              API Reference <ExternalLink size={11} style={{ display: 'inline', verticalAlign: 'middle' }} />
            </a>
            <a href="https://github.com/Santhoshjk159/DDI" target="_blank" rel="noopener noreferrer">
              Source Code <ExternalLink size={11} style={{ display: 'inline', verticalAlign: 'middle' }} />
            </a>
          </div>

          {/* Dataset */}
          <div className="footer-col">
            <p className="footer-col-title">Data Sources</p>
            <a href="https://ddinter.scbdd.com/" target="_blank" rel="noopener noreferrer">
              DDInter Database <ExternalLink size={11} style={{ display: 'inline', verticalAlign: 'middle' }} />
            </a>
            <a href="https://pubchem.ncbi.nlm.nih.gov/" target="_blank" rel="noopener noreferrer">
              PubChem <ExternalLink size={11} style={{ display: 'inline', verticalAlign: 'middle' }} />
            </a>
            <a href="https://go.drugbank.com/" target="_blank" rel="noopener noreferrer">
              DrugBank <ExternalLink size={11} style={{ display: 'inline', verticalAlign: 'middle' }} />
            </a>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="footer-disclaimer" role="note" aria-label="Medical disclaimer">
          <strong>⚠ Medical Disclaimer:</strong> This tool is intended for research and educational purposes only.
          Predictions are generated by a machine learning model based solely on molecular properties and should not
          be used as a substitute for professional clinical judgment, consultation with a licensed pharmacist,
          or approved medical references such as the BNF, Micromedex, or prescribing information sheets.
          Always consult a qualified healthcare professional before making prescribing decisions.
        </div>

        {/* Bottom bar */}
        <div className="footer-bottom">
          <p>© {year} DDIPredict Research Platform. All rights reserved.</p>
          <p>
            Powered by FastAPI · React · scikit-learn · PostgreSQL · Neon
          </p>
        </div>

      </div>
    </footer>
  )
}
